version: '2'
services:
    jhealthcheck-app:
        image: jhealthcheck
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhealthcheck-postgresql:5432/jhealthcheck
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhealthcheck-elasticsearch:9300
        ports:
            - 8080:8080
    jhealthcheck-postgresql:
        extends:
            file: postgresql.yml
            service: jhealthcheck-postgresql
    jhealthcheck-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhealthcheck-elasticsearch
